apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipe-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data/recipe"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-content-monitor-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/file_content_monitor"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-content-monitor-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-content-monitor
  labels:
    app: file-content-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-content-monitor
  template:
    metadata:
      labels:
        app: file-content-monitor
    spec:
      volumes:
      - name: recipe-storage
        persistentVolumeClaim:
          claimName: recipe-pvc
      - name: file-content-monitor-storage
        persistentVolumeClaim:
          claimName: file-content-monitor-pvc
      containers:
      - name: file-content-monitor
        image: mtweeman/hajle-silesia_file-content-monitor:latest
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: "project/recipe"
            name: recipe-storage
          - mountPath: "project/file_content_monitor"
            name: file-content-monitor-storage
---
apiVersion: v1
kind: Service
metadata:
  name: file-content-monitor
spec:
  selector:
    app: file-content-monitor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
